apiVersion: v1
kind: Service
metadata:
  name: contact-service
spec:
  selector:
    app: contact
  ports:
    - port: 8089
      targetPort: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
        - name: contact
          image: your-dockerhub/contact-service:latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "spring.datasource.url": "jdbc:mysql://mysql-contact-service:3306/contact_db?allowPublicKeyRetrieval=true&useSSL=false",
                  "spring.datasource.username": "root",
                  "spring.datasource.password": "root",
                  "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
                  "spring.jpa.hibernate.ddl-auto": "update",
                  "server.port": "8089",
                  "eureka.client.serviceUrl.defaultZone": "http://discovery-service:8761/eureka",
                  "management.endpoints.web.exposure.include": "*",
                  "management.endpoint.prometheus.enabled": "true",
                  "management.prometheus.metrics.export.enabled": "true",
                  "management.endpoint.health.show-details": "always",
                  "management.endpoint.metrics.enabled": "true"
                }
