apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: your-dockerhub/gateway-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"server.port":"8080","eureka.client.serviceUrl.defaultZone":"http://eureka:password@discovery-service:8761/eureka"}'
