apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login
  ports:
    - port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: your-dockerhub/login-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "spring.datasource.url": "jdbc:mysql://mysql-login-service:3306/login_db?allowPublicKeyRetrieval=true&useSSL=false",
                  "spring.datasource.username": "root",
                  "spring.datasource.password": "root",
                  "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
                  "spring.jpa.hibernate.ddl-auto": "update",
                  "server.port": "8084",
                  "eureka.client.serviceUrl.defaultZone": "http://discovery-service:8761/eureka",
                  "management.endpoints.web.exposure.include": "*",
                  "management.endpoint.prometheus.enabled": "true",
                  "management.prometheus.metrics.export.enabled": "true",
                  "management.endpoint.health.show-details": "always",
                  "management.endpoint.metrics.enabled": "true"
                }
