apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: your-dockerhub/order-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "spring.datasource.url": "jdbc:mysql://mysql-order-service:3306/order_db?allowPublicKeyRetrieval=true&useSSL=false",
                  "spring.datasource.username": "root",
                  "spring.datasource.password": "root",
                  "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
                  "spring.jpa.hibernate.ddl-auto": "update",
                  "server.port": "8086",
                  "eureka.client.serviceUrl.defaultZone": "http://discovery-service:8761/eureka",
                  "productStockUrl": "http://gateway-service:8080/tokkom/api/product/stock/",
                  "management.endpoints.web.exposure.include": "*",
                  "management.endpoint.prometheus.enabled": "true",
                  "management.prometheus.metrics.export.enabled": "true",
                  "management.endpoint.health.show-details": "always",
                  "management.endpoint.metrics.enabled": "true"
                }
